### PR TITLE
TEG REFORGED

### PR DESCRIPTION
**Pull request by Spyroshark**
## About The Pull Request

Adds back the Thermoelectric Generator. It is no longer a constructible machine, and instead can bought from cargo. Also features a new TGUI window.

New TGUI Window:
image

New sprites, also done by me:
image

I would be happy to hear any feedback about how the TEG feels balance wise. Keep in mind that because pumps now have entropy thanks to ZAS, keeping pressure difference in your circulators will be more tricky.
## Why It's Good For The Game

Fun engine. It's a crime to not include _the_ original engine of ss13.

## Changelog

:cl:
add: The Thermoelectric Generator is back! Now featuring a new UI. The parts for it can be bought from cargo.
/:cl:

### CODE REVIEW

**Comment by Spyroshark** [comment]
Oops.

**Comment by Kapu1178** [comment]
And on that day, Spyroshark learned to check which branch he was on.

**Review by Sirryan2002 — COMMENTED** [review]
a few stylistic things, would it be possible to see a screenshot of the TGUI?

**Comment by Spyroshark** [comment]
> a few stylistic things, would it be possible to see a screenshot of the TGUI?

image

Feast your eyes. I haven't made a brand new TGUI before but it works decently.

**Pull request merged**
