### PR TITLE
Goon Combat: Goodbye Despair

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Putting this up now so I don't forget and can easily keep track of my commits.

Features in the pipeline: 

- [X] Proper stamina regeneration
- [X] Stamina Stun replaces Stamina Crit
- [X] New status effect called "Disorient" to replace most forms of instant Stun/Paralyze/Knockdown
- [x] Stamina Weakened, or Exhaustion, a state where your melee swings become free, but you're exposed to Disorient stuns or Stamina Critical Knockouts!
- [X] Goon Crit
- [x] Stamina-based sprinting
- [x] Give items their own stamina costs per swing, and stamina damage
- [x] Stamina Stun, a "short" stun you receive when all of your stamina is drained
- [ ] Apply stamina costs to grabbing, as well as weight resist chance based on stamina
- [x] Overhaul disarms to remove wallstuns, deal stamina damage, and have weighted DISARM chance.
- [x] Stamina Critical Hits, most attacks can inflict a Stamina Critical, which deals double stamina damage, and can even knock out your target if they are Weakened!
- [x] Refactor grabbing to be represented by a held item
- [x] Add Pinning to grabs, a way to incapacitate a target completely, while being non-lethal.

An exerpt from discord:
Im seriously bored at work so here's a small write up of how the combat overhaul is going.

Ive completely rewritten stamina and removed it from the Life Loop. What this means is stamina will regenerate on 1 second intervals instead of 2, which improves responsiveness a ton. 

The basic mechanics of melee combat are in. All items deal some mixture of Brute and Stamina damage, and have variable Swing costs. I will be doing a balance pass at some point to improve improvised weapons.

Stamina Critical Hits work. All items have a critical hit rate and a critical modifier.

Soft Crit is now more of a bleeding out state than actually critical. You can walk at reduced speed, qnd still partake in a fight, but cannot speak and take mounting suffocation damage until you enter hard crit.

Stam Crit is gone and in its place is the Exhaustion State, Stamina Stun and Critical Knockout. When you drop below 40% stamina, you enter Exhaustion, where all attacks become free, but youre exposed to a Stam Stun or Critical Knockout. If you reach zero stamina, you will be stunned for a brief period, and rapidly regenerate stamina. If you recieve a Stamina Critical Hit during Exhaustion, you will be instantly knocked out cold!

Finally, Shoving has been changed. It has a high stamina cost, and deals low stamina damage. The kicker is that theres a chance to make your target drop their held items. The chance is weighted based on their current stamina, starting at 0 qnd capping out at 50%

Thats all i have coded so far, but im not done yet. Im working on a robust Sprinting mechanic, and after that hand to hand combat is getting a face lift, with pinning, chokeholds, limb dislocation. and neck snapping!

Oh, also, Flashes, Batons and Disablers work on a new Disorient mechanic, inspired by goon's mechanic of the same name. Insta stuns are going to be deleted. Disorient is a kind of "wrapper" for stamina damage. If the target is Exhausted and takes Disorient, they get a secondary effect determined by the caller. This is most often a short Knockdown. All of the status effect times are capped at 7 seconds, no permastuns here.

## Changelog

:cl: Kapu1178, mbc
!!To be filled out!!
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
good luck, I hope this won't be forgotten, because honestly screw baseline TG's crit system

**Comment by JohnFulpWillard** [comment]
Close this PR... NOW!

**Comment by Viz-Titan** [comment]
Amazing work 👍

**Comment by dwasint** [comment]
If this pin functions like what goons does i would recommend making it require 2 hands as once pinned you can just get smashed to death using the free hand

**Pull request closed without merging**
