### PR TITLE
Biobags hold extracts, new crates, fabricator fixes 

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Bio bags hold slime extracts again but cannot be equipped in any slot (on top of being bulky)

## Why It's Good For The Game

Makes moving extracts to the fridge less tedious while preventing people lugging around 999 oil and gold extracts

## Changelog

:cl:
balance: bio bags are unequippable on your belt, but hold slime extracts now
fix: fixed sec fabricator
fix: data disks now available as cargo crates
add: several new cargo packs to make lost designs attainable again
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
@Cenrus PR body is insufficient at describing changes.

**Review by Kapu1178 — CHANGES_REQUESTED** [review]
Undocumented changes

**Comment by Cenrus** [comment]
I didn't mean to push that commit. Can I consolidate this into the same PR?

**Comment by Kapu1178** [comment]
> I didn't mean to push that commit. Can I consolidate this into the same PR?

Ya sure, just need the desc and changelog updated.

**Pull request merged**
