### PR TITLE
Body Scanners+

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Body scanners have some new sprites and important information.

image

Now shows subject unique enzymes (DNA)
Blood type
Brain trauma types
Husked status
Bad DNA trait (changeling absorption)
Warns about undergoing cardiac arrest, as well as how to prevent it.

## Why It's Good For The Game

Less confusion and ambiguity for medical staff.

## Changelog

:cl:
add: Body scanners now reveal more information about patients
imgadd: New body scanner sprites added
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Much closer to what we want out of body scanners, wonderful.

**Comment by Kapu1178** [comment]
Not sure I like the sprite, feels incredibly out of place. As for the changes themselves, I'll pull them into the Brainmed PR and give credit, so you don't have to wait 10 years to see them in game, as they conflict with said PR.

**Comment by Cenrus** [comment]
ok, forget including the sprites if you dont like em

**Comment by francinum** [comment]
Agreed, Drop the sprite, it's an entirely different color palette from the console and isn't the style we're leaning towards.

Beyond that, looks good.

**Comment by Kapu1178** [comment]
Changes merged into Brainmed PR 👍

**Pull request closed without merging**
