### PR TITLE
MetaStation medbay fixes

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Fixes minor issues with the new medbay, mostly targeting disposals, phones, and minor decal work.
I took the opportunity to hide a telephone in maintenance that you can get working with a little effort. Can you find it? 

image

## Why It's Good For The Game

new medbay good
disposals bad

## Changelog

:cl:
fix: fixed disposals in the new MetaStation medbay
fix: added the chemdrobe back to MetaStation
fix: fixed the virology airlock controls not functioning
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
@Cenrus Could you drop a few photos in the body of the PR for where the chemdrobe and such are?

**Review by francinum — CHANGES_REQUESTED** [review]
@gonenoculer5 Check the diff actions.

Regardless, this is all mostly fine.

I was explicitly told to put warning tape striping on maintenance, you can blame kapu for that.

The breakroom looks pretty nice actually, I was running out of steam with that section. I don't know how I feel about it getting shutters though.

The morgue is just flat out better. That was a very last minute panic of 'oh shit I am out of room and have no idea where to shove this', though.

The lack of an organ fridge is intentional. Remove it.

**Comment by Cenrus** [comment]
> The lack of an organ fridge is intentional. Remove it.

I'll do that now. I placed one there since last I checked the freezer crates don't halt organ decay but now that I've checked the code, I see that they can.

Last commit should be in, I've added some holopads for the AI and given the CMO their suit back so let me know if you don't want any of that.

**Comment by francinum** [comment]
Rest of that should be fine

**Review by francinum — APPROVED** [review]

**Pull request merged**
