### PR TITLE
Return of syndicate bundles

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Return of syndicate surplus crates and syndie kits which have remained in the code completely unused.

Thanks to tgstation/tgstation/71869 for the updated surplus crate generation code

## Why It's Good For The Game

These were removed in the reputation traitor rework, I've missed them and think they're a good choice if you can't decide what to use your TC on.

## Changelog

:cl:
add: Returned syndicate surplus and super surplus crates to the uplink
add: Returned syndicate tactical and special kits to the uplink
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Iffy on letting these come back for balance reasons. @Kapu1178 @francinum @fighterslam

**Comment by francinum** [comment]
It's important to note that the code behind traitors is half-damage intentionally, and that behavior of it is... kinda weird at the moment.

**Comment by gonenoculer5** [comment]
@Cenrus Bump super surplus down to 100 TC, we'll see how it works, and if needed it will be bumped down to 80 TC. Otherwise this is fine to go.

**Comment by Cenrus** [comment]
reduced.

**Pull request merged**
