### PR TITLE
Splits up large hallway areas into smaller hallways

### PR DESCRIPTION
**Pull request by bluezorua**
## About The Pull Request
as it does on the tin, mostly splitting up metastations central hallway into 4 subsections and splitting the departures/aft hallway into two

## Why It's Good For The Game
image

## Changelog

:cl:
qol: Large metastation hallways (Central and Aft) have been split into smaller hallways to make atmos management easier.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Could you possibly provide an editor screenshot showing the area objects?

**Comment by bluezorua** [comment]
> Could you possibly provide an editor screenshot showing the area objects?

image
image

**Comment by francinum** [comment]
Thanks, looks good for the most part, but these areas can be anchored a lot better against reasonable geometry. See below.
----

**Comment by francinum** [comment]
Outside library, Overstacked tile, Move the APC behind the middle O2 closet.

**Comment by bluezorua** [comment]
image
done, APC movement was done on the previous commit

**Pull request merged**
