### PR TITLE
Extra functionality for sticky tape

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Ports tape GAGs, sprites, sounds and behaviour from tgstation/tgstation/pull/67713

Sticky tape can now be used to restrain people, or as a makeshift muzzle when targeting the mouth. Thanks to Spyro for suggesting this on the discord.

## Why It's Good For The Game

I felt like this behavior was missing, it's duct tape and should have more uses than just making items embed.

## Changelog

:cl: Ebb-Real, Cenrus
add: Tape can be used as makeshift handcuffs/muzzle when used on people
soundadd: Tape sound
add: handcuffed type is now shown on examine
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
Add to examine the new controls.

**Comment by Cenrus** [comment]
Hold on merge for now

**Comment by Cenrus** [comment]
👍

**Comment by francinum** [comment]
I'm confused why this isn't just standard attack behaviour when clicking mobs? The primary attack chain is unused.

**Comment by Cenrus** [comment]
Bot didn't remove the label

**Pull request merged**
