### PR TITLE
Redoes CentCom Z-Level to suit the aesthetic changes

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Changes lots of structures on the centcom level to fit the 3/4 sprite changes so it fits _immersion_ and is nice to look at.

## Why It's Good For The Game

Before:

before image

After:

image
image
image

## Changelog

:cl:
add: Centcom, operative base, and wizard den now look nicer.
/:cl:

### CODE REVIEW

**Review by francinum — APPROVED** [review]

**Comment by Kapu1178** [comment]
Will merge after the Engineering redo.

**Comment by gonenoculer5** [comment]
@Cenrus Could we adjust the color of the centcom plasma windows at all? They look a bit too purple/pink imo.

**Comment by Kapu1178** [comment]
merge master

**Comment by Kapu1178** [comment]
will tm 👍

**Pull request merged**
